import config as cfg
import wandb
import traceback
import os
import torch
import torch.multiprocessing as mp # Use torch.multiprocessing
from torch.utils.data import TensorDataset, DataLoader
from torchtnt.utils.data import CudaDataPrefetcher
from Training.jutils import ColorPrinter, Colors, wandb_login
from Data.data_loading_jaskin import load_and_preprocess_data, create_tensor_from_dataframe, create_sequences, VehiclePositionDataset, get_datasets
from Training.train_matt import Trainer
from NextNet.model_split import FrameTransformer
from Training.customLoss import ADELoss, FDELoss, RMSELoss, PaddedMSELoss
from datetime import datetime
import time

printer = ColorPrinter()

# Function to be executed by each worker process
def worker_function(
    assigned_gpu_id, # GPU assigned to this worker
    task_config_dict # Dictionary containing ALL configurations for this task
):
    run = None
    # Use model_name from task_config_dict for early prints
    model_name_for_print = task_config_dict.get('model_name', "Worker") 
    run_id_for_print = task_config_dict.get('run_id', "UnknownRunID")
    try:
        # 1. Setup device
        device = torch.device(f"cuda:{assigned_gpu_id}")

        # Construct run_name inside the worker, ensuring it's unique if desired
        run_name = f"{task_config_dict['model_name']}-gpu{assigned_gpu_id}-{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}"

        # Initialize W&B run in the worker using parameters from task_config_dict
        run = wandb.init(
            project=task_config_dict['wandb_project_name'],
            group=task_config_dict['wandb_group_name'],
            name=run_name,
            dir=os.path.join(task_config_dict['save_model_dir'], 'wandb'),
            id=task_config_dict['run_id'], # Use the unique ID generated by the main process
            config=task_config_dict, # Pass the full config dictionary from main
            reinit=True # Ensures this is treated as a new initialization context for this process
        )
        if not run:
            printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Failed to initialize W&B run with ID: {run_id_for_print}", Colors.RED)
            return # Cannot proceed without W&B run

        cfg_wandb = wandb.config # Now use wandb.config as the source of truth for params
        # Update model_name_for_print from the official wandb.config if it changed after init (e.g. if W&B modifies it)
        model_name_for_print = cfg_wandb.model_name 

        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Worker started. Initialized W&B run: {run.name} (ID: {run.id}). Using device: {str(device)}", Colors.CYAN)

        # 2. Create DataLoaders and Prefetchers (using cfg_wandb)
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Calling get_datasets with dataset_name: {cfg_wandb.dataset_name}", Colors.BLUE)
        train_dataset, test_dataset = get_datasets(
            csv_folder=cfg_wandb.cfg_csv_folder,
            sequence_offset=cfg_wandb.cfg_sequence_offset,
            sequence_length=cfg_wandb.cfg_sequence_length, # Global sequence length from config
            prediction_length=cfg_wandb.prediction_length, # Task-specific prediction length
            padding_token=cfg_wandb.cfg_padding_token,
            feauture_range=cfg_wandb.cfg_feature_range, # Note: original func has typo 'feauture_range'
            num_features=cfg_wandb.cfg_num_input_features,
            normalize=cfg_wandb.cfg_normalize_dataset,
            recompute=cfg_wandb.cfg_recompute_datasets,
            save=cfg_wandb.cfg_save_datasets,
            save_dir=cfg_wandb.cfg_dataset_save_dir,
            dataset_name=cfg_wandb.dataset_name # Dynamic name for this task's dataset cache
        )
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] get_datasets returned. Train dataset size: {len(train_dataset)}, Test dataset size: {len(test_dataset)}", Colors.GREEN)

        # Retrieve max_ids_per_frame from the dataset and update wandb config
        if hasattr(train_dataset, 'max_ids_per_frame') and train_dataset.max_ids_per_frame is not None:
            actual_num_ids = train_dataset.max_ids_per_frame
            wandb.config.update({"num_ids": actual_num_ids}, allow_val_change=True)
            printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Retrieved num_ids (max_ids_per_frame) from dataset: {actual_num_ids}", Colors.GREEN)
        else:
            printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] WARNING: Could not retrieve max_ids_per_frame from dataset. Model might use a default or incorrect value for num_ids.", Colors.YELLOW)
            # Fallback or error handling if num_ids is critical and not found
            # For now, we rely on wandb.config potentially having a default from the initial task_config_dict,
            # or the model having its own default. This should ideally be made more robust.
            # If num_ids was removed from task_config_dict, this will be an issue.
            # It's better to ensure get_datasets always provides it or raise an error.
            # If num_ids was removed from task_config_dict, this will be an issue.
            # It's better to ensure get_datasets always provides it or raise an error.
            if 'num_ids' not in cfg_wandb or cfg_wandb.num_ids is None: # Check if it was never set
                 raise ValueError(f"num_ids is critical but not found in dataset and not in wandb.config for task {model_name_for_print}")

        train_loader = DataLoader(
            train_dataset,
            batch_size=cfg_wandb.cfg_train_batch_size,
            prefetch_factor=cfg_wandb.cfg_num_train_batches_to_prefetch,
            shuffle=True,
            num_workers=cfg_wandb.cfg_num_workers * 2 // 3 if cfg_wandb.cfg_num_workers > 0 else 0,
            pin_memory=cfg_wandb.cfg_pin_memory,
            persistent_workers=True if cfg_wandb.cfg_num_workers > 0 else False
        )
        test_loader = DataLoader(
            test_dataset,
            batch_size=cfg_wandb.cfg_test_batch_size,
            prefetch_factor=cfg_wandb.cfg_num_test_batches_to_prefetch,
            shuffle=False,
            num_workers=cfg_wandb.cfg_num_workers // 3 if cfg_wandb.cfg_num_workers > 0 else 0,
            pin_memory=cfg_wandb.cfg_pin_memory,
            persistent_workers=True if cfg_wandb.cfg_num_workers > 0 else False
        )
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] DataLoaders created with {cfg_wandb.cfg_num_workers} workers.", Colors.GREEN)

        train_prefetcher = CudaDataPrefetcher(
            train_loader,
            device,
            num_prefetch_batches=cfg_wandb.cfg_num_train_batches_to_prefetch,
        )
        test_prefetcher = CudaDataPrefetcher(
            test_loader,
            device,
            num_prefetch_batches=cfg_wandb.cfg_num_test_batches_to_prefetch,
        )
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] CudaDataPrefetchers created.", Colors.GREEN)

        # 3. Instantiate Loss Functions
        loss_fn_map = {"ADELoss": ADELoss, "FDELoss": FDELoss, "RMSELoss": RMSELoss, "PaddedMSELoss": PaddedMSELoss}
        selected_loss_fn = loss_fn_map[cfg_wandb.loss_fn_class_name](reduction=cfg_wandb.loss_fn_reduction)
        selected_common_loss_fn = loss_fn_map[cfg_wandb.common_loss_fn_class_name](reduction=cfg_wandb.common_loss_fn_reduction)
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Loss functions instantiated.", Colors.GREEN)

        # 4. Instantiate Model
        model_kwargs_dict = dict(cfg_wandb.model_kwargs) if hasattr(cfg_wandb.model_kwargs, 'items') else {}

        model = FrameTransformer(
            input_feature_size=cfg_wandb.cfg_num_input_features,
            num_ids=cfg_wandb.num_ids, # Now sourced from dataset via wandb.config update
            sequence_length=cfg_wandb.cfg_sequence_length, # This is the global cfg.SEQUENCE_LENGTH
            prediction_length=cfg_wandb.prediction_length, # Task-specific prediction length
            **model_kwargs_dict
        ).to(device)
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Model FrameTransformer instantiated on {device}. Params: {sum(p.numel() for p in model.parameters())}", Colors.GREEN)

        # 5. Instantiate Trainer
        trainScript = Trainer(
            model,
            train_prefetcher,
            test_prefetcher,
            save_path=cfg_wandb.save_model_dir,
            model_name=cfg_wandb.model_name,
            device=device,
            wandb_run=run
        )
        trainScript.earlyStop(
            enable=True,
            patience=cfg_wandb.cfg_early_stopping_patience,
            delta=cfg_wandb.cfg_early_stopping_delta
        )
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Trainer initialized.", Colors.GREEN)

        # 6. Train
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Starting training for {cfg_wandb.num_epochs} epochs...", Colors.BLUE)
        optimizer_kwargs_dict = dict(cfg_wandb.optimizer_kwargs) if hasattr(cfg_wandb.optimizer_kwargs, 'items') else {}
        results_tuple = trainScript.train(
            num_epochs=cfg_wandb.num_epochs,
            learningRate=cfg_wandb.learning_rate,
            criterion=selected_loss_fn,
            optimizer=torch.optim.AdamW(model.parameters(), lr=cfg_wandb.learning_rate, **optimizer_kwargs_dict),
            common_loss_fn=selected_common_loss_fn
        )
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Training completed. Results: {results_tuple}", Colors.GREEN)

    except Exception as e:
        error_context = f"ERROR in worker_function for {model_name_for_print} (Run ID: {run_id_for_print}) on GPU {assigned_gpu_id}"
        printer.print(f"{error_context}: {type(e).__name__}: {e}", Colors.RED)
        error_traceback = traceback.format_exc()
        printer.print(error_traceback, Colors.RED)
        if run: 
            run.log({"error_type": type(e).__name__, "error_message": str(e), "traceback": error_traceback})
            run.finish(exit_code=1, quiet=True)
    finally:
        if run and run._exit_code is None: 
            run.finish(quiet=True)
            printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] W&B run {run.name} finished successfully.", Colors.BLUE)
        elif not run:
             printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Worker finished, W&B run was not properly initialized for Run ID: {run_id_for_print}.", Colors.YELLOW)
        printer.print(f"[{model_name_for_print} GPU:{assigned_gpu_id}] Worker finished.", Colors.CYAN)


def main():
    try:
        wandb_login() # Call W&B login once in the main process
    except Exception as e:
        printer.print(f"W&B login failed: {e}. Proceeding without W&B (if possible).", Colors.RED)

    wandb_project_name_global = "Deep-Learning-Project-Refactor"
    wandb_group_name_global = f"parallel_run_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    root_dir = os.getcwd()
    
    # Define num_features_global from config
    num_features_global = cfg.NUM_INPUT_FEATURES 
    printer.print(f"Global number of input features: {num_features_global}", Colors.CYAN)

    printer.print(f"Verifying cfg.CSV_FOLDER: {cfg.CSV_FOLDER}", Colors.CYAN)
    if not os.path.isdir(cfg.CSV_FOLDER):
        printer.print(f"Error: cfg.CSV_FOLDER='{cfg.CSV_FOLDER}' is not a valid directory. Please check config.py.", Colors.RED)
        return
    # Removed the call to load_and_preprocess_data to get transformer_max_ids_per_frame_main

    # Removed data_store and direct creation of X, Y tensors in main

    prediction_lengths_secs = [1, 2, 3, 4]

    # This list will hold the comprehensive config dictionaries for each task
    task_configs_list = [] 
    model_types = [
        {"name": "rmse_model", "loss": "RMSELoss", "common_loss": "ADELoss"},
        {"name": "ade_model", "loss": "ADELoss", "common_loss": "RMSELoss"},
    ]

    for model_type_info in model_types:
        for secs in prediction_lengths_secs:
            model_name = f"{model_type_info['name']}_{secs}s"
            X_key = f"X_{secs}s"
            Y_key = f"Y_{secs}s"
            
            dataset_name_for_task = f"dataset_pred{secs}s_seq{cfg.SEQUENCE_LENGTH}_norm{cfg.NORMALIZE_DATASET}"

            task_specific_config = {
                "run_id": wandb.util.generate_id(), # Unique ID for W&B run
                "wandb_project_name": wandb_project_name_global,
                "wandb_group_name": wandb_group_name_global,
                "model_name": model_name,
                "X_data_key": X_key, 
                "Y_data_key": Y_key, # This key is no longer used for data lookup in main
                "num_features": num_features_global, # Correctly using the defined variable
                "prediction_length": cfg.FPS * secs,
                "sequence_length": cfg.SEQUENCE_LENGTH, # Global sequence length, used by FrameTransformer
                "save_model_dir": os.path.join(root_dir, 'Model', 'Saved_Model_Refactor'),
                "model_kwargs": {'hidden_size': cfg.HIDDEN_SIZE, 'num_heads': cfg.NUM_HEADS, 'dropout_rate': cfg.DROPOUT_RATE},
                "loss_fn_class_name": model_type_info["loss"],
                "loss_fn_reduction": "mean",
                "common_loss_fn_class_name": model_type_info["common_loss"],
                "common_loss_fn_reduction": "mean",
                "learning_rate": cfg.LEARNING_RATE,
                "num_epochs": cfg.EPOCHS,
                "optimizer_kwargs": {},
                
                # Configs for get_datasets and DataLoaders
                "dataset_name": dataset_name_for_task,
                "cfg_csv_folder": cfg.CSV_FOLDER,
                "cfg_sequence_offset": cfg.SEQUENCE_OFFSET,
                "cfg_sequence_length": cfg.SEQUENCE_LENGTH, # Passed to get_datasets for sequence creation
                "cfg_padding_token": cfg.PADDING_TOKEN,
                "cfg_feature_range": cfg.FEATURE_RANGE,
                "cfg_num_input_features": cfg.NUM_INPUT_FEATURES,
                "cfg_normalize_dataset": cfg.NORMALIZE_DATASET,
                "cfg_recompute_datasets": cfg.RECOMPUTE_DATASETS,
                "cfg_save_datasets": cfg.SAVE_DATASETS,
                "cfg_dataset_save_dir": cfg.DATASET_SAVE_DIR,

                "cfg_num_workers": cfg.NUM_WORKERS,
                "cfg_train_batch_size": cfg.TRAIN_BATCH_SIZE,
                "cfg_test_batch_size": cfg.TEST_BATCH_SIZE,
                "cfg_pin_memory": cfg.PIN_MEMORY,
                "cfg_num_input_features": cfg.NUM_INPUT_FEATURES,
                "cfg_num_train_batches_to_prefetch": cfg.NUM_TRAIN_BATCHES_TO_PREFETCH,
                "cfg_num_test_batches_to_prefetch": cfg.NUM_TEST_BATCHES_TO_PREFETCH,
                "cfg_early_stopping_patience": cfg.EARLY_STOPPING_PATIENCE,
                "cfg_early_stopping_delta": cfg.EARLY_STOPPING_DELTA,
                # assigned_gpu_id will be added just before spawning the process
            }
            task_configs_list.append(task_specific_config)

    num_gpus_available = torch.cuda.device_count()
    num_gpus_to_use = min(cfg.NUM_GPUS_TO_USE, num_gpus_available)
    if num_gpus_to_use == 0:
        printer.print("No GPUs available or configured for use. Exiting.", Colors.RED)
        return
    printer.print(f"Number of GPUs to use: {num_gpus_to_use}", Colors.CYAN)

    try:
        if mp.get_start_method(allow_none=True) != 'spawn':
            mp.set_start_method('spawn', force=True)
            printer.print("Set multiprocessing start method to 'spawn'.", Colors.GREEN)
        else:
            printer.print("Multiprocessing start method already 'spawn'.", Colors.YELLOW)
    except RuntimeError as e:
        printer.print(f"Warning: Could not set start method to 'spawn': {e}. Current method: {mp.get_start_method(allow_none=True)}.", Colors.YELLOW)

    if not task_configs_list:
        printer.print("No tasks configured to run. Exiting.", Colors.RED)
        return

    active_processes_info = []
    task_queue_indices = list(range(len(task_configs_list)))
    available_gpu_ids = list(range(num_gpus_to_use))
    completed_task_count = 0

    printer.print(f"Starting training for {len(task_configs_list)} tasks using {num_gpus_to_use} GPUs.", Colors.CYAN)

    while completed_task_count < len(task_configs_list):
        while available_gpu_ids and task_queue_indices:
            gpu_id_to_use = available_gpu_ids.pop(0)
            current_task_idx = task_queue_indices.pop(0)
            
            # Get the base config for this task
            task_config_for_worker = task_configs_list[current_task_idx].copy()
            # Add/update the assigned_gpu_id in the config dict for the worker
            task_config_for_worker["assigned_gpu_id"] = gpu_id_to_use 
            
            # Arguments for the worker process
            args_for_worker = (
                gpu_id_to_use, # Passed directly for device selection convenience
                task_config_for_worker # The comprehensive config dictionary
            )
            current_run_id = task_config_for_worker['run_id'] # For print statement

            printer.print(f"Preparing to start task {task_config_for_worker['model_name']} (Run ID: {current_run_id}) on GPU {gpu_id_to_use} with dataset_name: {task_config_for_worker['dataset_name']}", Colors.BLUE)
            p = mp.Process(target=worker_function, args=args_for_worker)
            p.start()
            active_processes_info.append({
                'process': p,
                'gpu_id': gpu_id_to_use,
                'task_name': task_config_for_worker['model_name'],
                'pid': p.pid,
                'run_id': current_run_id
            })
            printer.print(f"Started task {task_config_for_worker['model_name']} (PID: {p.pid}, Run ID: {current_run_id}) on GPU {gpu_id_to_use}", Colors.GREEN)

        next_active_processes_info = []
        for proc_info in active_processes_info:
            p = proc_info['process']
            if not p.is_alive():
                exitcode = p.exitcode
                p.join() # Clean up
                printer.print(f"Process for task {proc_info['task_name']} (PID: {proc_info['pid']}, Run ID: {proc_info['run_id']}) on GPU {proc_info['gpu_id']} finished. Exit code: {exitcode}", Colors.GREEN if exitcode == 0 else Colors.YELLOW)
                available_gpu_ids.append(proc_info['gpu_id'])
                completed_task_count += 1
            else:
                next_active_processes_info.append(proc_info)
        active_processes_info = next_active_processes_info

        if completed_task_count == len(task_configs_list):
            break
        time.sleep(1)

    printer.print(f"All {len(task_configs_list)} training tasks completed.", Colors.BOLD_GREEN)

if __name__ == '__main__':
    main()